language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t visakhg/docker-react .

script:
  - docker run -e CI=true visakhg/docker-react npm run test -- --coverage
